Snapshot before fixing KeyError
KeyError: "The name 'TfPoseEstimator/Openpose/concat_stage7:0' refers to a Tensor which does not exist. The operation, 'TfPoseEstimator/Openpose/concat_stage7', does not exist in the graph."